# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [63]:
# your code here
import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder

# Read `tic-tac-toe.csv` into a dataframe.
df = pd.read_csv("tic-tac-toe.csv")
cat_columns = df.columns[:-1]
le = LabelEncoder()
for col in cat_columns:
    df[col] = le.fit_transform(df[col])

df = df.astype(float)

# Separate the inputs and output
X = df.drop(columns=["class"])
y = df["class"]

# Normalize with TensorFlow
X = tf.keras.utils.normalize(X, axis=1)

print(X)
X = X.numpy()



tf.Tensor(
[[0.40824829 0.40824829 0.40824829 ... 0.40824829 0.20412415 0.20412415]
 [0.40824829 0.40824829 0.40824829 ... 0.20412415 0.40824829 0.20412415]
 [0.40824829 0.40824829 0.40824829 ... 0.20412415 0.20412415 0.40824829]
 ...
 [0.20412415 0.40824829 0.20412415 ... 0.40824829 0.20412415 0.40824829]
 [0.20412415 0.40824829 0.20412415 ... 0.40824829 0.20412415 0.40824829]
 [0.20412415 0.20412415 0.40824829 ... 0.20412415 0.40824829 0.40824829]], shape=(958, 9), dtype=float64)


## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [64]:
# your code here
# Split the training and test data.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Create a `Sequential` model.
model = tf.keras.models.Sequential()
# Add several layers to your model.
model.add(tf.keras.layers.Flatten())
#  Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers.
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dense(128, activation='relu'))
# Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
model.add(tf.keras.layers.Dense(10, activation='softmax'))
# Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
# Fit the training data.
model.fit(X_train, y_train, epochs=3)

# Evaluate your neural network model with the test data.
val_loss, val_acc = model.evaluate(X_test, y_test)
# Save your model as `tic-tac-toe.model`.
model.save('tic-tac-toe.keras')



Epoch 1/3
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4389 - loss: 2.0016       
Epoch 2/3
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.8802 
Epoch 3/3
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6599 - loss: 0.6486 
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6538 - loss: 0.6447 


## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [65]:
# your code here
import numpy as np
# load your saved model 
new_model = tf.keras.models.load_model('tic-tac-toe.keras')

predictions = new_model.predict(X_test)

print(np.argmax(predictions[5]))

# Evaluate the loaded model on the test data
loss, accuracy = new_model.evaluate(X_test, y_test)

print(f"Test Loss: {loss}")
print(f"Test Accuracy: {accuracy}")


6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
1
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6538 - loss: 0.6447  
Test Loss: 0.6412374377250671
Test Accuracy: 0.6666666865348816


## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [66]:
# your code here
model_3 = tf.keras.models.Sequential()
# Add several layers to your model.
model_3.add(tf.keras.layers.Flatten())
#  Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers.
model_3.add(tf.keras.layers.Dense(128, activation='relu'))
model_3.add(tf.keras.layers.Dense(128, activation='relu'))
model_3.add(tf.keras.layers.Dense(128, activation='relu'))
model_3.add(tf.keras.layers.Dense(128, activation='relu'))
# Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
model_3.add(tf.keras.layers.Dense(10, activation='softmax'))
# Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001) 

model_3.compile(optimizer=optimizer,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
# Fit the training data.
model_3.fit(X_train, y_train, epochs=10)

loss, accuracy = model_3.evaluate(X_test, y_test)
print(f"Test Loss: {loss}")
print(f"Test Accuracy: {accuracy}")



Epoch 1/10
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6313 - loss: 1.8627
Epoch 2/10
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5658 - loss: 0.7047 
Epoch 3/10
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6593 - loss: 0.6389 
Epoch 4/10
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6621 - loss: 0.6278 
Epoch 5/10
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7044 - loss: 0.6226 
Epoch 6/10
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7013 - loss: 0.5876 
Epoch 7/10
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7368 - loss: 0.5484 
Epoch 8/10
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7509 - loss: 0.5199 
Epoch 9/10
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7862 - loss: 0.5040 
Epoch 10/10
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7760 - loss: 0.4766 
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7246 - loss: 0.5619 
Test Loss: 0.5801542401313782
Test Accuracy: 0.734375


**Which approach(es) did you find helpful to improve your model performance?**

In [ ]:
# your answer here

# additional layers seemed to improve the acuracy